package com.hull.busflow.po.lottery;

import com.hull.busflow.common.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class UserProbability extends BaseEntity {
  private Integer upId;
  /**
  用户id
  **/
  private String userId;
  /**
  奖项id
  **/
  private Integer acpzId;
  /**
  人员对奖项的中奖概率
  **/
  private BigDecimal upProbability;
  private Date upCreateTime;
  private Date upUpdateTime;

  public Integer getUpId() {
  	return upId;
  }
	
  public void setUpId(Integer upId) {
    this.upId = upId;
  }
	
  public String getUserId() {
  	return userId;
  }
	
  public void setUserId(String userId) {
    this.userId = userId;
  }
	
  public Integer getAcpzId() {
  	return acpzId;
  }
	
  public void setAcpzId(Integer acpzId) {
    this.acpzId = acpzId;
  }
	
  public BigDecimal getUpProbability() {
  	return upProbability;
  }
	
  public void setUpProbability(BigDecimal upProbability) {
    this.upProbability = upProbability;
  }
	
  public Date getUpCreateTime() {
  	return upCreateTime;
  }
	
  public void setUpCreateTime(Date upCreateTime) {
    this.upCreateTime = upCreateTime;
  }
	
  public Date getUpUpdateTime() {
  	return upUpdateTime;
  }
	
  public void setUpUpdateTime(Date upUpdateTime) {
    this.upUpdateTime = upUpdateTime;
  }
	
}
