package com.hull.destiny.common.entity;

import com.hull.destiny.common.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class LotDrawRecord extends BaseEntity {
  private Integer drawRecordId;
  /**
  用户id
  **/
  private String userId;
  /**
  活动id
  **/
  private Integer activityId;
  /**
  抽奖时间
  **/
  private Date drawTime;

  public Integer getDrawRecordId() {
  	return drawRecordId;
  }
	
  public void setDrawRecordId(Integer drawRecordId) {
    this.drawRecordId = drawRecordId;
  }
	
  public String getUserId() {
  	return userId;
  }
	
  public void setUserId(String userId) {
    this.userId = userId;
  }
	
  public Integer getActivityId() {
  	return activityId;
  }
	
  public void setActivityId(Integer activityId) {
    this.activityId = activityId;
  }
	
  public Date getDrawTime() {
  	return drawTime;
  }
	
  public void setDrawTime(Date drawTime) {
    this.drawTime = drawTime;
  }
	
}
