package com.mljr.destiny.common.entity;

import com.mljr.destiny.common.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class LotItemPrizeRela extends BaseEntity {
  private Integer lipId;
  /**
  活动奖项id
  **/
  private Integer lipAitId;
  /**
  奖品id
  **/
  private Integer lipPriId;
  private Integer lipTotal;
  /**
  奖项包含的奖品数量
  **/
  private Integer lipAccount;
  private Date lipUpdateTime;
  private Date lipCreateTime;

  public Integer getLipId() {
  	return lipId;
  }
	
  public void setLipId(Integer lipId) {
    this.lipId = lipId;
  }
	
  public Integer getLipAitId() {
  	return lipAitId;
  }
	
  public void setLipAitId(Integer lipAitId) {
    this.lipAitId = lipAitId;
  }
	
  public Integer getLipPriId() {
  	return lipPriId;
  }
	
  public void setLipPriId(Integer lipPriId) {
    this.lipPriId = lipPriId;
  }
	
  public Integer getLipTotal() {
  	return lipTotal;
  }
	
  public void setLipTotal(Integer lipTotal) {
    this.lipTotal = lipTotal;
  }
	
  public Integer getLipAccount() {
  	return lipAccount;
  }
	
  public void setLipAccount(Integer lipAccount) {
    this.lipAccount = lipAccount;
  }
	
  public Date getLipUpdateTime() {
  	return lipUpdateTime;
  }
	
  public void setLipUpdateTime(Date lipUpdateTime) {
    this.lipUpdateTime = lipUpdateTime;
  }
	
  public Date getLipCreateTime() {
  	return lipCreateTime;
  }
	
  public void setLipCreateTime(Date lipCreateTime) {
    this.lipCreateTime = lipCreateTime;
  }
	
}
