package com.hull.destiny.po.lottery;

import com.hull.destiny.common.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class LotActivityOrg extends BaseEntity {
  private Integer actId;
  /**
  活动名称
  **/
  private String actName;
  /**
  活动开始时间
  **/
  private Date actStartTime;
  /**
  活动结束时间
  **/
  private Date actEndTime;
  /**
  活动状态：1:开启;2:关闭
  **/
  private String actStatus;
  /**
  活动类型1:随机抽奖;2:秒杀
  **/
  private String actType;
  /**
  活动抽奖次数
  **/
  private Integer actDrawnum;
  /**
  库存为空时概率变动方式：1:增加其他奖品中奖概率；2降低其他奖品中奖概率
  **/
  private Integer actProbType;
  private Date actUpdateTime;
  private Date actCreateTime;

  public Integer getActId() {
  	return actId;
  }
	
  public void setActId(Integer actId) {
    this.actId = actId;
  }
	
  public String getActName() {
  	return actName;
  }
	
  public void setActName(String actName) {
    this.actName = actName;
  }
	
  public Date getActStartTime() {
  	return actStartTime;
  }
	
  public void setActStartTime(Date actStartTime) {
    this.actStartTime = actStartTime;
  }
	
  public Date getActEndTime() {
  	return actEndTime;
  }
	
  public void setActEndTime(Date actEndTime) {
    this.actEndTime = actEndTime;
  }
	
  public String getActStatus() {
  	return actStatus;
  }
	
  public void setActStatus(String actStatus) {
    this.actStatus = actStatus;
  }
	
  public String getActType() {
  	return actType;
  }
	
  public void setActType(String actType) {
    this.actType = actType;
  }
	
  public Integer getActDrawnum() {
  	return actDrawnum;
  }
	
  public void setActDrawnum(Integer actDrawnum) {
    this.actDrawnum = actDrawnum;
  }
	
  public Integer getActProbType() {
  	return actProbType;
  }
	
  public void setActProbType(Integer actProbType) {
    this.actProbType = actProbType;
  }
	
  public Date getActUpdateTime() {
  	return actUpdateTime;
  }
	
  public void setActUpdateTime(Date actUpdateTime) {
    this.actUpdateTime = actUpdateTime;
  }
	
  public Date getActCreateTime() {
  	return actCreateTime;
  }
	
  public void setActCreateTime(Date actCreateTime) {
    this.actCreateTime = actCreateTime;
  }
	
}
