package com.hull.destiny.po.lottery;

import com.hull.destiny.common.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class LotActivityItemRela extends BaseEntity {
  private Integer aitItemId;
  /**
  活动id
  **/
  private Integer aitActivityId;
  /**
  奖品总数
  **/
  private Integer aitTotal;
  /**
  奖品库存
  **/
  private Integer aitInventory;
  /**
  奖项中奖概率
  **/
  private BigDecimal aitProbability;
  private Date aitUpdateTime;
  private Date aitCreateTime;

  public Integer getAitItemId() {
  	return aitItemId;
  }
	
  public void setAitItemId(Integer aitItemId) {
    this.aitItemId = aitItemId;
  }
	
  public Integer getAitActivityId() {
  	return aitActivityId;
  }
	
  public void setAitActivityId(Integer aitActivityId) {
    this.aitActivityId = aitActivityId;
  }
	
  public Integer getAitTotal() {
  	return aitTotal;
  }
	
  public void setAitTotal(Integer aitTotal) {
    this.aitTotal = aitTotal;
  }
	
  public Integer getAitInventory() {
  	return aitInventory;
  }
	
  public void setAitInventory(Integer aitInventory) {
    this.aitInventory = aitInventory;
  }
	
  public BigDecimal getAitProbability() {
  	return aitProbability;
  }
	
  public void setAitProbability(BigDecimal aitProbability) {
    this.aitProbability = aitProbability;
  }
	
  public Date getAitUpdateTime() {
  	return aitUpdateTime;
  }
	
  public void setAitUpdateTime(Date aitUpdateTime) {
    this.aitUpdateTime = aitUpdateTime;
  }
	
  public Date getAitCreateTime() {
  	return aitCreateTime;
  }
	
  public void setAitCreateTime(Date aitCreateTime) {
    this.aitCreateTime = aitCreateTime;
  }
	
}
