package com.hull.destiny.po.lottery;

import com.hull.destiny.common.BaseEntity;

import java.util.Date;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class LotWinPrizeRecord extends BaseEntity {
  private Integer winRecordId;
  /**
  中奖用户id
  **/
  private String userId;
  /**
  活动id
  **/
  private Integer activityId;
  /**
  奖项id
  **/
  private Integer acpzId;
  /**
  中奖时间
  **/
  private Date winTime;
  /**
  是否领奖 0:未领奖 1：已领奖
  **/
  private Integer isClaim;
  private Date claimTime;
  /**
  用户抽奖记录表id
  **/
  private Integer drawRecordId;
  private Date winUpdateTime;
  private Date winCreateTime;

  public Integer getWinRecordId() {
  	return winRecordId;
  }
	
  public void setWinRecordId(Integer winRecordId) {
    this.winRecordId = winRecordId;
  }
	
  public String getUserId() {
  	return userId;
  }
	
  public void setUserId(String userId) {
    this.userId = userId;
  }
	
  public Integer getActivityId() {
  	return activityId;
  }
	
  public void setActivityId(Integer activityId) {
    this.activityId = activityId;
  }
	
  public Integer getAcpzId() {
  	return acpzId;
  }
	
  public void setAcpzId(Integer acpzId) {
    this.acpzId = acpzId;
  }
	
  public Date getWinTime() {
  	return winTime;
  }
	
  public void setWinTime(Date winTime) {
    this.winTime = winTime;
  }
	
  public Integer getIsClaim() {
  	return isClaim;
  }
	
  public void setIsClaim(Integer isClaim) {
    this.isClaim = isClaim;
  }
	
  public Date getClaimTime() {
  	return claimTime;
  }
	
  public void setClaimTime(Date claimTime) {
    this.claimTime = claimTime;
  }
	
  public Integer getDrawRecordId() {
  	return drawRecordId;
  }
	
  public void setDrawRecordId(Integer drawRecordId) {
    this.drawRecordId = drawRecordId;
  }
	
  public Date getWinUpdateTime() {
  	return winUpdateTime;
  }
	
  public void setWinUpdateTime(Date winUpdateTime) {
    this.winUpdateTime = winUpdateTime;
  }
	
  public Date getWinCreateTime() {
  	return winCreateTime;
  }
	
  public void setWinCreateTime(Date winCreateTime) {
    this.winCreateTime = winCreateTime;
  }
	
}
